dist: trusty
sudo: require
language: cpp
compiler: gcc
addons:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - gcc-6
    - g++-6
    - cmake

script:
  # setup
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - gcc -v && g++ -v && cmake --version
  - cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-6 -DCMAKE_CXX_COMPILER=/usr/bin/g++-6
  # build commands
  - cmake .
  - make
  - ./tests/tests
