dist: trusty
sudo: require
language: cpp
compiler: gcc
addons:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - gcc-6
    - g++-6
    - cmake

script:
  # setup
  - export CC=gcc-6
  - export CXX=g++-6
  - gcc -v && g++ -v && cmake --version
  # build commands
  - cmake .
  - make
  - ./tests/tests
